---
title: "EPL_24"
author: "Deambrogio"
date: "4/25/2025"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

```{r}
pass_EPL_24<- read.csv("pass_EPL_24.csv")
pass_EPL_23<- read.csv("pass_EPL_23.csv")
pass_ITA_24<- read.csv("pass_ITA_24.csv")
pass_ITA_23<- read.csv("pass_ITA_23.csv")

all_pass <- rbind(
  pass_EPL_24,
  pass_EPL_23,
  pass_ITA_24,
  pass_ITA_23
)
dim(all_pass)
```


```{r}
all_pass_summary <- all_pass %>%
  group_by(Game_URL) %>%
  summarise(
    HomeTeam              = first(`Home_Team`),
    AwayTeam              = first(`Away_Team`),
    Home_better           = as.integer(first(Home_xG) > first(Away_xG)),
    HomePass_to_AwayPass  = Cmp_Total[Home_Away == "Home"] /
                             Cmp_Total[Home_Away == "Away"],
    HomePass_to_AwayPass_short =
      Cmp_Short[Home_Away == "Home"] /
      Cmp_Short[Home_Away == "Away"],
  ) %>%
  ungroup()

head(all_pass_summary)
```


```{r}
# Fit logistic model
log_mod <- glm(
  Home_better ~ HomePass_to_AwayPass,
  data   = all_pass_summary,
  family = 'binomial'
)

# View the coefficient estimates, p-values, etc.
summary(log_mod)

if (F) {
exp(coef(log_mod))
1/(1+exp(0.62170))
1/(1+exp(0.4440-0.6644*1))
}
```

```{r}
# Fit logistic model
log_mod2 <- glm(
  Home_better ~ HomePass_to_AwayPass_short,
  data   = all_pass_summary,
  family = 'binomial'
)

# View the coefficient estimates, p-values, etc.
summary(log_mod2)
```

```{r}
ggplot(all_pass_summary, aes(x = "", y = HomePass_to_AwayPass_short)) +
  geom_boxplot() +
  labs(
    x     = NULL,
    y     = "HomePass_to_AwayPass_short",
    title = "Boxplot of HomePass_to_AwayPass_short"
  ) +
  theme_minimal()

# Boxplot for HomePass_to_AwayPass
ggplot(all_pass_summary, aes(x = "", y = HomePass_to_AwayPass)) +
  geom_boxplot() +
  labs(
    x     = NULL,
    y     = "HomePass_to_AwayPass",
    title = "Boxplot of HomePass_to_AwayPass"
  ) +
  theme_minimal()

```

```{r}
ggplot(all_pass_summary, aes(x = HomePass_to_AwayPass_short)) +
  geom_histogram(binwidth = 0.1, boundary = 0, closed = "left") +
  labs(
    x     = "HomePass_to_AwayPass_short",
    y     = "Count",
    title = "Distribution of HomePass_to_AwayPass_short"
  ) +
  theme_minimal()

# Histogram for HomePass_to_AwayPass
ggplot(all_pass_summary, aes(x = HomePass_to_AwayPass)) +
  geom_histogram(binwidth = 0.1, boundary = 0, closed = "left") +
  labs(
    x     = "HomePass_to_AwayPass",
    y     = "Count",
    title = "Distribution of HomePass_to_AwayPass"
  ) +
  theme_minimal()
```

```{r}
ggplot(all_pass, aes(x = Att_Short, y = Cmp_percent_Long)) +
  geom_point(alpha = 0.6) +
  labs(
    x = "Short-Pass Attempts (Att_Short)",
    y = "Long-Pass Completion Rate (%) (Cmp_percent_Long)",
    title = "Long-Pass Completion vs Short-Pass Attempts"
  ) +
  theme_minimal()
```

